### ISSUE TITLE
Request for the elephant’s trunk nebula image

### ISSUE THREAD

**Issue by liuzhen0212** [jwcho5576/streamable_nf#1]
Hi, thanks for your great work!
Could your please share **the elephant’s trunk nebula image** shown in Fig. 1 and Fig. 7？

**Comment by jwcho5576** [comment]
Thank you for reaching me out!
I used the image in wikipedia:
https://en.m.wikipedia.org/wiki/File:Elephant%27s_Trunk_nebula.jpg
I used the image size of 2560x1984.

Thank you.
Junwoo Cho

2024년 4월 29일 (월) 오후 10:08, Zhen Liu ***@***.***>님이 작성:
